version: '2'

services:
  api:
    image: node:latest
    environment:
      - NODE_ENV=production
    volumes:
      - ./api:/app
    working_dir: /app
    command: npm start
    networks:
      - database
      - default

  management:
    image: node:latest
    environment:
      - NODE_ENV=production
      - API_ADDRESS=//api.cromoly.com
      - STATIC_ADDRESS=//static.cromoly.com
    volumes:
      - ./management:/app
    working_dir: /app
    command: npm run dev
    networks:
      - default
    links:
      - api
  website:
    image: node:latest
    environment:
      - NODE_ENV=production
      - API_ADDRESS=http://api:3000
    volumes:
      - ./website:/app
    working_dir: /app
    command: npm start
    networks:
      - default
    links:
      - api

  proxy:
    image: node:latest
    environment:
      - NODE_ENV=production
    volumes:
      - ./proxy:/app
    working_dir: /app
    command: npm start
    networks:
      - default
    ports:
      - "80:80"
      - "443:443"
    links:
      - api
      - website

networks:
  database:
    external: true
