version: '2'

services:
  api:
    image: node:latest
    restart: always
    environment:
      - VIRTUAL_HOST=api.cromoly.com
      - VIRTUAL_PROTO=http
      - LETSENCRYPT_HOST=api.cromoly.com
      - LETSENCRYPT_EMAIL=dany@cromoly.com
      - NODE_ENV=production
    volumes:
      - ./api:/app
    working_dir: /app
    command: npm start
    expose: 
      - "3000"
    networks:
      - database
      - default
      - nginx-proxy

  management:
    image: node:latest
    restart: always
    environment:
      - VIRTUAL_HOST=management.cromoly.com
      - VIRTUAL_PROTO=http
      - LETSENCRYPT_HOST=management.cromoly.com
      - LETSENCRYPT_EMAIL=dany@cromoly.com
      - NODE_ENV=production
      - API_ADDRESS=//api.cromoly.com
    volumes:
      - ./management:/app
    working_dir: /app
    command: npm start
    expose:
      - "3000"
    networks:
      - default
      - nginx-proxy
    links:
      - api

  website:
    image: node:latest
    restart: always
    environment:
      - VIRTUAL_HOST=web.cromoly.com
      - VIRTUAL_PROTO=http
      - NODE_ENV=production
      - API_ADDRESS=http://api:3000
    volumes:
      - ./website:/app
    working_dir: /app
    command: npm start
    expose:
      - "3000"
    networks:
      - default
      - nginx-proxy
    links:
      - api

networks:
  database:
    external: true
  nginx-proxy:
    external: true
